services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - DATABASE_URL=postgresql://postgres:password@db:5432/e-track
    ports:
      - "5000:5000"
    volumes:
      - ./app:/app
      - ./static:/app/static
      - ./media:/app/media
    depends_on:
      - db

  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: e-track
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:

#healthcheck?